[deps]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSONFBCModels = "475c1105-d6ed-49c1-9b32-c11adca6d3e8"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"

[compat]
Documenter = "0.26"
Literate = "2.8"
